database:
  host: test.com
  database-name: test
  username: root
  password: password

subreddits:
  linuxmasterrace:
    submissions: 50 #select 50 submissions
    timing: 60 #get data every 60 seconds
    sort-by-section: hot #hot, top, controversial; defaults to hot if not any of those
    sort-by-time: today #only works with controversial and top; hour, day, week, month, year, all

track-posts:
  1234: 20 # post-id: how many seconds between each data collection


reddit:
  client-id: dsds
  client-secret: dsa
  user-agent: dsafvfd